### ISSUE TITLE
Works in development mode, fails when packaged into VSIX

### ISSUE THREAD

**Issue by domesticmouse** [domesticmouse/vscode-typer#1]
To create a installable VSIX package:

1. Clone this repository
1. `npm i` to install dependencies
1. `npm run package` to build `vscode-typer-0.0.3.vsix`

Install in your closest Visual Studio Code instance. Then attempt to run "Reset Main" command, and you'll see `command 'extension.devFestResetMain' not found`

**Comment by PeterWone** [comment]
For reasons I cannot yet fathom, VS Code is not finding the entry point. How did you create this project -- did you use `yo code` or did you manually create everything?

**Comment by domesticmouse** [comment]
Good question. I followed some form of tutorial some where. If rebuilding it atop `yo code` boilerplate will fix this issue I'll happily go down that path.

**Comment by domesticmouse** [comment]
Turns out the issue was that I had a dependency in the dev dependencies list when it should have been a full dependency. Thus it failed at run time because the dependency was missing.

Fixed in https://github.com/domesticmouse/vscode-typer/commit/33179cbf86b89fbede579f84791a9f322aab36e4

**Comment by PeterWone** [comment]
Well, there's one for the record books. In hindsight it's obvious -- what's the main difference between debug and deployed? Dev dependencies aren't loaded.

**Comment by PeterWone** [comment]
Well, there's one for the record books. In hindsight it's obvious -- what's the main difference between debug and deployed? Dev dependencies aren't loaded.

**Comment by domesticmouse** [comment]
Turns out running code with verbose logging is the way to enlightenment 🥳

**Comment by PeterWone** [comment]
How did you make vscode load an installed extension with verbose logging?

**Comment by domesticmouse** [comment]
It required a couple of steps:
 - Package up the extension with `vsce package`
 - Run `code --verbose`
 - Install the package using `code`'s package UI
 - Instantiate the package after the log display had gone quiet so I could figure out which error messages were my fault.
 - The logs complained about missing `diff`, which was the moment of enlightenment ;-)

**Comment by PeterWone** [comment]
So the procedure for investigating "works in debug, fails when installed" would be

1. Set up the extension so that activation is interactively triggered.
2. Re-install the extension with a version bump to avoid cache problems.
3. Wait for messages to stop and clear the message pane.
4. Trigger activation and observe the error messages.

**Comment by domesticmouse** [comment]
SGTM =)

**Comment by ankitpriyarup** [comment]
Hi! I'm also facing the same issue with my LSP extension in VS Code
https://github.com/ankitpriyarup/GDScript_LSP_Extension

**Comment by PeterWone** [comment]
@ankitpriyarup  So look at your dev dependencies to see what should be in production dependencies.

**Comment by ankitpriyarup** [comment]
@PeterWone I tried that didn't work for me, can you have a look at my package.json?

**Comment by ankitpriyarup** [comment]
Nevermind it worked! I had to package it from client

**Comment by MikeMannox** [comment]
@domesticmouse Could you please make this available on the [Marketplace](https://marketplace.visualstudio.com/) or at least add VSIX to Releases.

THANKS!!

**Comment by domesticmouse** [comment]
@MikeMannox this is very much a tool that I hack on for my presentational needs, I haven't put any thought into what is required to support other users actually using this tooling.

**Comment by ignatandrei** [comment]
Bump to put into Marketplace
